version: '3.5'

services:
  postgresql:
    image: bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: bitnami/airflow-scheduler:2.2.5
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
            # Uncomment to include custom plugins
      - ./plugins:/opt/bitnamei/airflow/plugins
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__CORE__FERNET_KEY= '81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs='
  airflow-worker:
    image: bitnami/airflow-worker:2.2.5
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
            # Uncomment to include custom plugins
      - ./plugins:/opt/bitnamei/airflow/plugins
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__CORE__FERNET_KEY= '81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs='
  airflow:
    image: bitnami/airflow:2.2.5
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
            # Uncomment to include custom plugins
      - ./plugins:/opt/bitnamei/airflow/plugins
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY= '81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs='
    ports:
      - '8080:8080'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local



